import {
  BadRequestException,
  Controller,
  Get,
  Module,
  Param,
  Post,
  Query,
} from '@nestjs/common';
import { Store, StoreModule } from '../store/store.module';
import { Auth, AuthContext, RequirePermission } from '../auth/auth-context';
import { GithubService } from './github.service';
import { buildRemediationMarkdown } from './remediation';

@Controller('projects/:projectId')
class GithubController {
  constructor(
    private readonly github: GithubService,
    private readonly store: Store,
  ) {}

  /**
   * Open a pull request adding a remediation plan (built from the latest scan's
   * findings + recommendations) to the connected repo. Findings are
   * architecture-level, so this lands a reviewed plan rather than editing source.
   */
  @Post('remediation-pr')
  @RequirePermission('connection:write')
  async remediationPr(
    @Auth() auth: AuthContext,
    @Param('projectId') projectId: string,
  ) {
    const scans = await this.store.listScans(projectId);
    const latest = scans.find((s) => s.status === 'succeeded') ?? scans[0];
    if (!latest) {
      throw new BadRequestException('Run a scan first to generate a plan.');
    }
    const markdown = buildRemediationMarkdown(latest);
    return this.github.openPullRequest(projectId, auth.org.id, {
      path: 'RISCLY_REMEDIATION.md',
      content: markdown,
      title: 'Riscly: remediation plan',
      body:
        'Automated remediation plan generated by Riscly from the latest scan. ' +
        'Review the prioritized risks and recommended fixes below.',
    });
  }

  /** Recent commits across the project's connected GitHub repos. */
  @Get('commits')
  @RequirePermission('project:read')
  commits(
    @Auth() auth: AuthContext,
    @Param('projectId') projectId: string,
    @Query('limit') limit?: string,
  ) {
    const n = Math.min(Math.max(Number(limit) || 10, 1), 30);
    return this.github.listCommits(projectId, auth.org.id, n);
  }

  /** The file tree (blob paths) for a repo, for the code explorer. */
  @Get('files')
  @RequirePermission('project:read')
  async files(
    @Auth() auth: AuthContext,
    @Param('projectId') projectId: string,
    @Query('repo') repo?: string,
  ) {
    const repos = await this.github.listRepos(projectId, auth.org.id);
    const target = repo && repos.includes(repo) ? repo : repos[0];
    if (!target) return { repo: null, repos, files: [] };
    const files = await this.github.listFiles(projectId, auth.org.id, target);
    return { repo: target, repos, files };
  }

  /** Raw UTF-8 content of a single file. */
  @Get('files/content')
  @RequirePermission('project:read')
  async fileContent(
    @Auth() auth: AuthContext,
    @Param('projectId') projectId: string,
    @Query('repo') repo: string,
    @Query('path') path: string,
  ) {
    const content = await this.github.readFile(
      projectId,
      auth.org.id,
      repo,
      path,
    );
    return { repo, path, content };
  }
}

@Module({
  imports: [StoreModule],
  controllers: [GithubController],
  providers: [GithubService],
  exports: [GithubService],
})
export class GithubModule {}
